"""tron_wallet_model

Revision ID: cb0a1edb47cb
Revises: 
Create Date: 2025-07-30 17:35:06.011457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0a1edb47cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tron_wallet',
    sa.Column('address', sa.String(length=34), nullable=False),
    sa.Column('trx_balance', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('bandwidth', sa.Integer(), nullable=True),
    sa.Column('bandwidth_limit', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('energy_limit', sa.Integer(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tron_wallet_address'), 'tron_wallet', ['address'], unique=False)
    op.create_index(op.f('ix_tron_wallet_created_at'), 'tron_wallet', ['created_at'], unique=False)
    op.create_index(op.f('ix_tron_wallet_updated_at'), 'tron_wallet', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tron_wallet_updated_at'), table_name='tron_wallet')
    op.drop_index(op.f('ix_tron_wallet_created_at'), table_name='tron_wallet')
    op.drop_index(op.f('ix_tron_wallet_address'), table_name='tron_wallet')
    op.drop_table('tron_wallet')
    # ### end Alembic commands ###
